vich_uploader:
    db_driver: orm
    mappings:
        path_file:
             uri_prefix: /images/path
             upload_destination: '%upload_directory%'
        walking_file:
            uri_prefix: /images/walking
            upload_destination: '%upload_directory%'
