vich_uploader:
    db_driver: orm

    mappings:
        walking_file:
            uri_prefix: /images/walking
            upload_destination: '%upload_directory%'
        home_file:
            uri_prefix: /images/home
            upload_destination: '%upload_directory%'

